global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]

  - job_name: "microservices"
    metrics_path: /metrics
    dns_sd_configs:
      - names:
          - tasks.monitoring
        type: "A"
        port: 9090
    static_configs:
      - targets: []
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/*.yml
        refresh_interval: 30s